FROM node:22.14.0-bookworm AS install
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM install AS build 
WORKDIR /app
COPY tsconfig*.json ./
COPY angular.json ./
COPY public ./public
COPY src ./src
RUN npm run build

FROM nginx:alpine AS deploy
COPY --chown=644 nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/gdp-app/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]