FROM node:25-alpine AS install
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM install AS build
WORKDIR /app
COPY tsconfig*.json ./
COPY angular.json ./
COPY public ./public
COPY src ./src
RUN npm run build

FROM nginx:1.29-alpine-slim AS deploy
COPY --chown=root:root nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/gdp-app/browser /usr/share/nginx/html
ENV API_URL=http://node:3000
EXPOSE 80

# Correct env.js path
CMD sed -i "s|http://localhost:3000|$API_URL|" /usr/share/nginx/html/public/env.js && \
    nginx -g "daemon off;"
