FROM node:22.14.0-bookworm AS install
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM install AS build
WORKDIR /app
COPY tsconfig*.json ./
COPY angular.json ./
COPY public ./public
COPY src ./src
RUN npm run build

FROM nginx:alpine AS deploy
WORKDIR /usr/share/nginx/html
COPY --chown=root:root nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/gdp-app/browser .
ENV API_URL=http://node:3000
EXPOSE 80

# Correct env.js path
CMD sed -i "s|http://localhost:3000|$API_URL|" /usr/share/nginx/html/public/env.js && \
    nginx -g "daemon off;"
